package demo.fruit.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "fruit")
public class Fruit extends BaseDTO {
      @Id
      @GeneratedValue(generator = "IDENTITY")
      @Column(name = "f_id")
      private Long id;

      @Column(name = "f_name")
      @Condition(operator = "LIKE")
      private String name;

      @Column(name = "f_price")
      private Long price;

      @Column(name = "f_producing_area")
      private String producingArea;

     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setPrice(Long price){
         this.price = price;
     }

     public Long getPrice(){
         return price;
     }

     public void setProducingArea(String producingArea){
         this.producingArea = producingArea;
     }

     public String getProducingArea(){
         return producingArea;
     }
     }
